name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake lcov libssl-dev
        
    - name: Configure and build with coverage
      run: |
        mkdir build
        cd build
        cmake -DENABLE_COVERAGE=ON ..
        make
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate coverage report
      run: |
        cd build
        make coverage
        # List what was actually generated
        echo "Contents of build directory:"
        ls -la
        echo "Contents of coverage_report directory (if exists):"
        ls -la coverage_report/ || echo "coverage_report directory does not exist"
        echo "Contents of coverage.info file:"
        ls -la coverage.info || echo "coverage.info file does not exist"
        
    - name: Upload coverage report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          ./build/coverage.info
          ./build/coverage_report/
        if-no-files-found: ignore
        
    - name: Upload all build files as artifact (fallback)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: all-build-files
        path: |
          ./build/**
        if-no-files-found: ignore
        
    - name: Comment PR with coverage instructions
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Code Coverage Report\n\nThe coverage report generation has completed and artifacts have been uploaded to the [workflow run](${artifactUrl}).\n\nTo view the HTML report:\n1. Download the \`coverage-report\` artifact from the workflow run\n2. Extract the archive\n3. Open \`coverage_report/index.html\` in your browser\n\nThe coverage report includes detailed information about code coverage for all tests.`
          });